package main

// quotes is a collection of tech-related quotes displayed randomly in the UI.
var quotes = []string{
	`"Any sufficiently advanced technology is indistinguishable from magic." — Arthur C. Clarke`,
	`"Talk is cheap. Show me the code." — Linus Torvalds`,
	`"The best way to predict the future is to invent it." — Alan Kay`,
	`"First, solve the problem. Then, write the code." — John Johnson`,
	`"Simplicity is the soul of efficiency." — Austin Freeman`,
	`"It works on my machine." — Every developer, ever`,
	`"There are only two hard things in CS: cache invalidation and naming things." — Phil Karlton`,
	`"The most dangerous phrase is: We've always done it this way." — Grace Hopper`,
	`"Perfection is achieved not when there is nothing more to add, but nothing left to take away." — Saint-Exupéry`,
	`"UNIX is simple. It just takes a genius to understand its simplicity." — Dennis Ritchie`,
	`"Debugging is twice as hard as writing the code in the first place." — Brian Kernighan`,
	`"Premature optimization is the root of all evil." — Donald Knuth`,
	`"The function of good software is to make the complex appear to be simple." — Grady Booch`,
	`"Good code is its own best documentation." — Steve McConnell`,
	`"Before software can be reusable it first has to be usable." — Ralph Johnson`,
	`"Make it work, make it right, make it fast." — Kent Beck`,
	`"Code is like humor. When you have to explain it, it's bad." — Cory House`,
	`"Programs must be written for people to read, and only incidentally for machines to execute." — Abelson & Sussman`,
	`"Any fool can write code that a computer can understand. Good programmers write code that humans can understand." — Martin Fowler`,
	`"The computer was born to solve problems that did not exist before." — Bill Gates`,
	`"Software is a great combination of artistry and engineering." — Bill Gates`,
	`"Nine people can't make a baby in a month." — Fred Brooks`,
	`"A language that doesn't affect the way you think about programming is not worth knowing." — Alan Perlis`,
	`"The most disastrous thing you can ever learn is your first programming language." — Alan Kay`,
	`"Computers are useless. They can only give you answers." — Pablo Picasso`,
	`"The best error message is the one that never shows up." — Thomas Fuchs`,
	`"One man's crappy software is another man's full-time job." — Jessica Gaston`,
	`"It's not a bug — it's an undocumented feature." — Anonymous`,
	`"The Internet is becoming the town square for the global village of tomorrow." — Bill Gates`,
	`"We are all now connected by the Internet, like neurons in a giant brain." — Stephen Hawking`,
	`"The only truly secure system is one that is powered off." — Gene Spafford`,
	`"With great power comes great responsibility." — Uncle Ben / Voltaire`,
	`"rm -rf / — Trust me, I'm an engineer." — Anonymous`,
	`"There is no cloud. It's just someone else's computer." — Anonymous`,
	`"I don't always test my code, but when I do, I do it in production." — Anonymous`,
	`"Works on my machine. Ship it." — Anonymous`,
	`"To iterate is human, to recurse divine." — L. Peter Deutsch`,
	`"Weeks of coding can save you hours of planning." — Anonymous`,
	`"Software and cathedrals are much the same — first we build them, then we pray." — Sam Redwine`,
	`"The best thing about a boolean is even if you are wrong, you are only off by a bit." — Anonymous`,
	`"If debugging is the process of removing bugs, then programming must be the process of putting them in." — Edsger Dijkstra`,
	`"Deleted code is debugged code." — Jeff Sickel`,
	`"Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live." — John Woods`,
	`"I have not failed. I've just found 10,000 ways that won't work." — Thomas Edison`,
	`"The only way to do great work is to love what you do." — Steve Jobs`,
	`"Stay hungry, stay foolish." — Steve Jobs`,
	`"Real artists ship." — Steve Jobs`,
	`"Move fast and break things." — Mark Zuckerberg`,
	`"Hardware: the parts of a computer that can be kicked." — Jeff Pesis`,
	`"The Internet? Is that thing still around?" — Homer Simpson`,
	`"I think there is a world market for maybe five computers." — Thomas Watson, IBM, 1943`,
	`"640K ought to be enough for anybody." — Bill Gates, 1981 (disputed)`,
	`"Perl: the only language that looks the same before and after RSA encryption." — Keith Bostic`,
	`"PHP is a minor evil perpetrated by incompetent amateurs." — Rasmus Lerdorf`,
	`"There are only 10 types of people: those who understand binary and those who don't." — Anonymous`,
	`"A SQL query walks into a bar, sees two tables and asks: Can I JOIN you?" — Anonymous`,
	`"Why do Java developers wear glasses? Because they don't C#." — Anonymous`,
	`"How many programmers does it take to change a light bulb? None. That's a hardware problem." — Anonymous`,
	`"!false — it's funny because it's true." — Anonymous`,
	`"I'd love to change the world, but they won't give me the source code." — Anonymous`,
	`"Home is where the WiFi connects automatically." — Anonymous`,
	`"Machine intelligence is the last invention that humanity will ever need to make." — Nick Bostrom`,
	`"The question of whether computers can think is like the question of whether submarines can swim." — Dijkstra`,
	`"People worry that computers will get too smart. The real problem is they're too stupid." — Pedro Domingos`,
	`"AI is the new electricity." — Andrew Ng`,
	`"The best minds of my generation are thinking about how to make people click ads." — Jeff Hammerbacher`,
	`"When something is important enough, you do it even if the odds are not in your favor." — Elon Musk`,
	`"I'm doing things that are difficult and important. That's what makes them fun." — Elon Musk`,
	`"It's fine to celebrate success but it is more important to heed the lessons of failure." — Bill Gates`,
	`"Imagination is more important than knowledge." — Albert Einstein`,
	`"Logic will get you from A to B. Imagination will take you everywhere." — Albert Einstein`,
	`"Life is too short to run proprietary software." — Richard Stallman`,
	`"Given enough eyeballs, all bugs are shallow." — Linus's Law / Eric Raymond`,
	`"Information wants to be free." — Stewart Brand`,
	`"The Street finds its own uses for things." — William Gibson`,
	`"Cyberspace. A consensual hallucination." — William Gibson`,
	`"The future is already here — it's just not evenly distributed." — William Gibson`,
	`"Never trust a computer you can't throw out a window." — Steve Wozniak`,
	`"The only legitimate use of a computer is to play games." — Eugene Jarvis`,
	`"In a world without fences and walls, who needs Gates and Windows?" — Anonymous`,
	`"Linux is only free if your time has no value." — Jamie Zawinski`,
	`"Measuring programming progress by lines of code is like measuring aircraft building progress by weight." — Bill Gates`,
	`"The cloud is just someone else's computer having a bad day." — Anonymous`,
	`"There's no place like 127.0.0.1." — Anonymous`,
	`"sudo make me a sandwich." — xkcd`,
	`"I'm not slacking off. My code is compiling." — xkcd`,
	`"SELECT * FROM users WHERE clue > 0; — 0 rows returned." — Anonymous`,
	`"It compiles; ship it." — Anonymous`,
	`"A good programmer looks both ways before crossing a one-way street." — Anonymous`,
	`"The code you write makes you a programmer. The code you delete makes you a good one." — Mario Fusco`,
	`"Every great developer you know got there by solving problems they were unqualified to solve." — Patrick McKenzie`,
	`"The most important property of a program is whether it accomplishes the intentions of its user." — C.A.R. Hoare`,
	`"Simplicity is prerequisite for reliability." — Edsger Dijkstra`,
	`"Programming is the art of telling another human what one wants the computer to do." — Donald Knuth`,
	`"The only constant in technology is change." — Anonymous`,
	`"chmod 777 — because security is for the weak." — Anonymous`,
	`"May your coffee be strong and your build times short." — Anonymous`,
	`"Keep calm and git push --force." — Anonymous`,
	`"99 little bugs in the code, 99 little bugs. Take one down, patch it around — 127 little bugs in the code." — Anonymous`,
}
